// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBLi91p4CeMLtEPy7oDQmxC7cuX-P0dfs',
    appId: '1:549852662693:web:f5c326e56e86123224764c',
    messagingSenderId: '549852662693',
    projectId: 'pythonquiz-9e58a',
    authDomain: 'pythonquiz-9e58a.firebaseapp.com',
    storageBucket: 'pythonquiz-9e58a.appspot.com',
    measurementId: 'G-CKX83TEVL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy6-1g4anwUkHl8jKA8MRvGGC3q7YIXkk',
    appId: '1:549852662693:android:6b48754ec342746b24764c',
    messagingSenderId: '549852662693',
    projectId: 'pythonquiz-9e58a',
    storageBucket: 'pythonquiz-9e58a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV3TEMrTU4twLZAoylIl3TSCB_rl2Jlh0',
    appId: '1:549852662693:ios:9afe7fb29580b14624764c',
    messagingSenderId: '549852662693',
    projectId: 'pythonquiz-9e58a',
    storageBucket: 'pythonquiz-9e58a.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV3TEMrTU4twLZAoylIl3TSCB_rl2Jlh0',
    appId: '1:549852662693:ios:9afe7fb29580b14624764c',
    messagingSenderId: '549852662693',
    projectId: 'pythonquiz-9e58a',
    storageBucket: 'pythonquiz-9e58a.appspot.com',
    iosBundleId: 'com.example.untitled',
  );
}
